services:
  runner:
    build:
      context: .
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    ports:
      - "2222:22"
    networks:
      runner:
        ipv4_address: 172.20.0.10
    extra_hosts:
      - "gitlab.ddragos.com:192.168.0.238"

networks:
  runner:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
